### ISSUE TITLE
Sort chat list

### ISSUE THREAD

**Issue by Salomon-MH** [AAA-Intelligence/eve#103]
Sort the list of  chats according to the time (when the last message was sent) and the bot creation (new bot creations should be sorted like last message timestamp).

E.g.:
Bot A: Last Message: 03:02 PM
Bot B: Last Message: 01:34 PM
Bot C: No messages, created: 02:13 PM

Expected order:
A, C, B

**Comment by niklaskorz** [comment]
Ist fertig
