### ISSUE TITLE
Add delay so answers always take at least 2 or 5 seconds

### ISSUE THREAD

**Issue by niklaskorz** [AAA-Intelligence/eve#111]
This should probably go into the Go server. Thoughts?
@KeKsBoTer

**Comment by niklaskorz** [comment]
I guess 2 seconds are more reasonable

**Comment by daniel-scholz** [comment]
Response time doesnt need to be consistent (compare to real answers, which depend on the message’s length), so: 2 secs at least. Everything above is okey
