### ISSUE TITLE
Flashing connection lost popup on reload

### ISSUE THREAD

**Issue by KeKsBoTer** [AAA-Intelligence/eve#115]
![bug](https://user-images.githubusercontent.com/14186588/39085197-7867f44a-457f-11e8-82bd-5b677e098f24.gif)

**Comment by Salomon-MH** [comment]
I can't reproduce this issue, checked with different browsers.
The popup shows up when the websocket is closed, so seems like your browser closes the session and still updates the site on refresh, which is weird...
Please provide some information on your config.

**Comment by Salomon-MH** [comment]
Added a general delay for the disconnect popup.
@KeKsBoTer Please check if the bug still persists for you or if that fixed it for you.
