### ISSUE TITLE
Please explain how fill up  bot/chat-data dir

### ISSUE THREAD

**Issue by remotejob** [AAA-Intelligence/eve#130]
Please explain how fill up  bot/chat-data dir
Thanks

**Comment by Salomon-MH** [comment]
Hey there!
Please check the [wiki](https://github.com/AAA-Intelligence/eve/wiki) to see how to set up the bot.
Regarding your question you might especially check out the ["Training the models" wiki page](https://github.com/AAA-Intelligence/eve/wiki/Training-the-models).
If you have any further questions do not hesitate to ask us. 👍🏼
