### ISSUE TITLE
Create pattern recognizer

### ISSUE THREAD

**Issue by LeonErath** [AAA-Intelligence/eve#24]
The pattern recognizer shall detect certain sentence pattern which triggers a static respond. 

Example: a joke

**Comment by niklaskorz** [comment]
https://chatbotsmagazine.com/contextual-chat-bots-with-tensorflow-4391749d0077

**Comment by niklaskorz** [comment]
https://sourcedexter.com/tensorflow-text-classification-python/

**Comment by niklaskorz** [comment]
http://www.nltk.org/api/nltk.stem.html
