### ISSUE TITLE
Create Web UI.

### ISSUE THREAD

**Issue by LeonErath** [AAA-Intelligence/eve#31]
Das Absenden einer Nachricht über das UI, führt zum Weiterleiten der Nachricht über den Web Socket an den Request Handler. Alle Nachrichten des Bots werden an den Web Socket gesendet, welcher diese an das UI weitergeleitet und somit für den User sichtbar  macht.

<img width="396" alt="screen shot 2018-03-13 at 08 54 19" src="https://user-images.githubusercontent.com/16130008/37328947-2a471144-269c-11e8-85cd-9d125ddd239f.png">
<img width="492" alt="screen shot 2018-03-13 at 08 54 25" src="https://user-images.githubusercontent.com/16130008/37328948-2a659db2-269c-11e8-93be-ee3290d34ca0.png">

**Comment by Salomon-MH** [comment]
Todo:

- [ ] Style for registration
- [ ] Style for new bot settings

**Comment by Salomon-MH** [comment]
- [ ] Select image
- [ ] Generate Name
- [ ] Select Gender
- [ ] Get all data via JSON
- [ ] Correctly submit data to creation handler

**Comment by Salomon-MH** [comment]
- [X] Profiles for bots (click on image or name when in chat)
- [X] Mobile and responsive design
- [X] Handling of empty bot lists (new user)
- [ ] User friendly disconnect message

**Comment by Salomon-MH** [comment]
Done. #86
