### ISSUE TITLE
Create Text Processor (generative model)

### ISSUE THREAD

**Issue by LeonErath** [AAA-Intelligence/eve#34]
Interface between the Request Handler and TensorFlow.

**Comment by niklaskorz** [comment]
Generates an answer if a predefined answer couldn't be made (i.e., if no pattern was recognized). Uses a generative model for generating the answer.

**Comment by niklaskorz** [comment]
https://github.com/bshao001/ChatLearner

**Comment by niklaskorz** [comment]
Should probably be renamed from "text processor" to something more specific.
