### ISSUE TITLE
Create Mood Analyzer.

### ISSUE THREAD

**Issue by LeonErath** [AAA-Intelligence/eve#35]
Sollte es sich nicht um eine Benutzereingabe mit vordefinierter Antwort halten, so wird eine Antwort mit Hilfe der durch TensorFlow trainierten künstlichen Intelligenz generiert. Dabei werden die Stimmung sowie Zuneigung (Mood Analyzer) berücksichtigt, die der Nutzer mit seiner Nachricht vermittelt. Dies geschieht erneut über Mustererkennung auf Basis eines Datensatzes, der Nachrichten bestimmter Stimmungen und Zuneigungen enthält (siehe Aufbau der Lerndaten).

**Comment by daniel-scholz** [comment]
basic mood analyzer is finished..
only datasets have to be improved
