### ISSUE TITLE
Format code and fix code style

### ISSUE THREAD

**Issue by niklaskorz** [AAA-Intelligence/eve#48]
Before the end of the project, we should ensure a consistent code style throughout the project (i.e., gofmt style for all Go files, an agreed style for all CSS and HTML files and PEP 8 for all Python files).

**Comment by niklaskorz** [comment]
For Python, PEP-8 and Pylint are the styles most commonly used:

- https://www.python.org/dev/peps/pep-0008/
- https://www.pylint.org/

**Comment by niklaskorz** [comment]
Go has its own tool for ensuring a consistent code style:

- https://golang.org/cmd/gofmt/

**Comment by Salomon-MH** [comment]
5a10b9a
Fixed indentation for CSS file.
