### ISSUE TITLE
Create database if eve.sqlite does not exist

### ISSUE THREAD

**Issue by niklaskorz** [AAA-Intelligence/eve#64]
If no database file is found (i.e., eve.sqlite does not exist), a new one should be created and saved based on db-script.sql at the start of the Go server.

**Comment by Salomon-MH** [comment]
The same code shouldnt be saved twice. See script.sql vs. Script.go.
Maybe read the first file in the go file?

**Comment by KeKsBoTer** [comment]
#80 Solved
