### ISSUE TITLE
Button display error if no bot exists

### ISSUE THREAD

**Issue by KeKsBoTer** [AAA-Intelligence/eve#81]
![Screenshot](https://user-images.githubusercontent.com/14186588/38519055-dba407f0-3c3e-11e8-9403-7a42cc2b9cd9.png)

**Comment by KeKsBoTer** [comment]
![ss 2018-04-09 at 09 41 08](https://user-images.githubusercontent.com/14186588/38519088-f4a059b6-3c3e-11e8-9e66-d8f597ad7f33.png)

**Comment by Salomon-MH** [comment]
Done with #86
