### ISSUE TITLE
Bot does not answer questions about parents right

### ISSUE THREAD

**Issue by KeKsBoTer** [AAA-Intelligence/eve#83]
![Screenshot](https://user-images.githubusercontent.com/14186588/38521299-8f8b239c-3c45-11e8-8a3a-118ffcbfd9b1.png)

**Comment by niklaskorz** [comment]
Should be fixed by https://github.com/AAA-Intelligence/eve/pull/85/commits/5e3575b7c5cba08d564f75e3aed9d2bb952c2209
