### ISSUE TITLE
Deliver Software

### ISSUE THREAD

**Issue by LeonErath** [AAA-Intelligence/eve#98]

**Comment by LeonErath** [comment]
[ ] - Testprotokolle anfertigen
[ ] - Produkt abschicken incl. Protokolle und Dokumentationen
[ ] - Projekttagebuch abgeben
[ ] - Produkt + trainierten Modell
[ ] - Link zum Parser schicke
[ ] - Eingangsbestätigung bei Kunden Mail
[ ] - Auflistung der pattern Kategorien und Eingaben

**Comment by LeonErath** [comment]
[EVE Kundenpräsentation 24_04_2018.pdf](https://github.com/AAA-Intelligence/eve/files/1938421/EVE.Kundenprasentation.24_04_2018.pdf)

**Comment by LeonErath** [comment]
[EVE Teampräsentation 23_04_2018.pdf](https://github.com/AAA-Intelligence/eve/files/1938431/EVE.Teamprasentation.23_04_2018.pdf)

**Comment by LeonErath** [comment]
We need to export all our Documentation to pdf. Either through an markdown to pdf converter or something else.

**Comment by daniel-scholz** [comment]
[Projekttagebücher_ProjektEve_23_04_2018_v1.pdf](https://github.com/AAA-Intelligence/eve/files/1939230/Projekttagebucher_ProjektEve_23_04_2018_v1.pdf)

**Comment by LeonErath** [comment]
[Predefined Answers Categories 23_04_2018.pdf](https://github.com/AAA-Intelligence/eve/files/1939374/Predefined.Answers.Categories.Kruse.pdf)

**Comment by niklaskorz** [comment]
@daniel-scholz separat ist glaube ich besser, würde die nicht mergen
